### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by LanderU** [ros-realtime/ros-realtime-rpi4-image#45]
```bash
/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image
[2022-07-30 14:37:35][INFO] running run_phase1_target_scripts 
[2022-07-30 14:37:35][DEBUG] copying /home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/image_builder/data/focal-rt/scripts/phase1-target to /tmp/rpi4-image-build/setup/phase1-target
[2022-07-30 14:37:35][DEBUG] running ['systemd-nspawn', '-D', '/tmp/rpi4-image-build', 'env', 'CACHE_DIR=/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/cache', 'OUT_DIR=/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/out', 'CHROOT_PATH=/tmp/rpi4-image-build', 'LINUX_RT_VERSION=5.4.195-rt74', 'STOCK_LINUX_VERSION=5.4.0-1052', 'PINNED_CPU_FREQUENCY=1500000', 'ROS_DISTRO=galactic', '/setup/phase1-target'] in the target
Spawning container rpi4-image-build on /tmp/rpi4-image-build.
Press ^] three times within 1s to kill container.
/bin/env: '/setup/phase1-target': Permission denied
Container rpi4-image-build failed with error code 126.
Traceback (most recent call last):
  File "./ros-rt-img", line 133, in <module>
    main()
  File "./ros-rt-img", line 129, in main
    args.action(args)
  File "./ros-rt-img", line 86, in build
    builder.build()
  File "/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/image_builder/builder.py", line 163, in build
    self.run_step(self.run_phase1_target_scripts)
  File "/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/image_builder/builder.py", line 307, in run_step
    f()
  File "/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/image_builder/builder.py", line 262, in run_phase1_target_scripts
    self._run_script_on_target(phase1_target_path)
  File "/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/image_builder/builder.py", line 410, in _run_script_on_target
    subprocess.run(cmd, check=True, env=self.env_vars)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['systemd-nspawn', '-D', '/tmp/rpi4-image-build', 'env', 'CACHE_DIR=/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/cache', 'OUT_DIR=/home/runner/work/ros-realtime-rpi4-image/ros-realtime-rpi4-image/out', 'CHROOT_PATH=/tmp/rpi4-image-build', 'LINUX_RT_VERSION=5.4.195-rt74', 'STOCK_LINUX_VERSION=5.4.0-1052', 'PINNED_CPU_FREQUENCY=1500000', 'ROS_DISTRO=galactic', '/setup/phase1-target']' returned non-zero exit status 126.
make: *** [Makefile:6: focal-rt-ros2] Error 1
Error: Process completed with exit code 2.
```

**Comment by LanderU** [comment]
FYI @shuhaowu @carlossvg

**Comment by shuhaowu** [comment]
I saw it, not sure why it doesn't have permission.  Will need to investigate.

**Comment by carlossvg** [comment]
@shuhaowu This happens locally too when building focal

**Comment by shuhaowu** [comment]
Will need to look into it. I'm pretty busy this week so no promise it'll be fixed this week.
